package Pck_View;

import Pkg_Controle.FuncoesControle;


public class IndexView extends javax.swing.JFrame {

    public void limpar() {
        jTextAreaResultado.setText("");
        jTextAreaReceptor.setText("");
    }
    public IndexView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        jPanelSecundario = new javax.swing.JPanel();
        jLabelCodificar = new javax.swing.JLabel();
        jLabelDecodificar = new javax.swing.JLabel();
        jLabelLimpar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaReceptor = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(24, 39, 55));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Codificador e decodificador de textos");
        jLabelTitulo.setFocusable(false);

        jLabelSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubtitulo.setText("Use nossa ferramenta para mandar mensagens secretas");
        jLabelSubtitulo.setFocusable(false);

        jPanelSecundario.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCodificar.setBackground(new java.awt.Color(24, 39, 55));
        jLabelCodificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCodificar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodificar.setText("Codificar");
        jLabelCodificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabelCodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCodificar.setFocusable(false);
        jLabelCodificar.setOpaque(true);
        jLabelCodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCodificarMouseClicked(evt);
            }
        });

        jLabelDecodificar.setBackground(new java.awt.Color(24, 39, 55));
        jLabelDecodificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDecodificar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDecodificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDecodificar.setText("Decodificar");
        jLabelDecodificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabelDecodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDecodificar.setFocusable(false);
        jLabelDecodificar.setOpaque(true);
        jLabelDecodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDecodificarMouseClicked(evt);
            }
        });

        jLabelLimpar.setBackground(new java.awt.Color(24, 39, 55));
        jLabelLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLimpar.setText("Limpar");
        jLabelLimpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabelLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLimpar.setFocusable(false);
        jLabelLimpar.setOpaque(true);
        jLabelLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLimparMouseClicked(evt);
            }
        });

        jTextAreaReceptor.setColumns(20);
        jTextAreaReceptor.setLineWrap(true);
        jTextAreaReceptor.setRows(5);
        jTextAreaReceptor.setText("Coloque seu texto ou código aqui!");
        jScrollPane2.setViewportView(jTextAreaReceptor);

        jTextAreaResultado.setColumns(20);
        jTextAreaResultado.setLineWrap(true);
        jTextAreaResultado.setRows(5);
        jTextAreaResultado.setText("Veja seu resultado aqui!");
        jScrollPane1.setViewportView(jTextAreaResultado);

        javax.swing.GroupLayout jPanelSecundarioLayout = new javax.swing.GroupLayout(jPanelSecundario);
        jPanelSecundario.setLayout(jPanelSecundarioLayout);
        jPanelSecundarioLayout.setHorizontalGroup(
            jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                .addGroup(jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabelCodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDecodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelSecundarioLayout.setVerticalGroup(
            jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDecodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabelSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLimparMouseClicked
        limpar();
    }//GEN-LAST:event_jLabelLimparMouseClicked

    private void jLabelCodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCodificarMouseClicked
        
        FuncoesControle obj = new FuncoesControle();
        String texto, codigo;
        
        texto = jTextAreaReceptor.getText();
        codigo = obj.lerTexto(texto);
        jTextAreaResultado.setText(codigo);

    }//GEN-LAST:event_jLabelCodificarMouseClicked

    private void jLabelDecodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDecodificarMouseClicked
        
        FuncoesControle obj = new FuncoesControle();
        String texto, codigo;
        
        codigo = jTextAreaReceptor.getText();
        texto = obj.lerCodigo(codigo);
        jTextAreaResultado.setText(texto);
        
    }//GEN-LAST:event_jLabelDecodificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCodificar;
    private javax.swing.JLabel jLabelDecodificar;
    private javax.swing.JLabel jLabelLimpar;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSecundario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaReceptor;
    private javax.swing.JTextArea jTextAreaResultado;
    // End of variables declaration//GEN-END:variables
}
